# Copyright (c) 2017 Genome Research Ltd.
#
# Authors:
# * Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---

# vault contents:
# arvados_cluster_sso_google_oauth_client_id
# arvados_cluster_sso_google_oauth_client_secret
# arvados_cluster_git_ssh_private_key
# arvados_cluster_mercury_shell_ssh_private_key

arvados_cluster_root_key: "{{ arvados_cluster_git_ssh_private_key }}"

# generate credentials from the root key
arvados_cluster_db_password_sso: "{{ arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_db_password_sso', 16) | b36encode }}"
arvados_cluster_db_password_api: "{{ arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_db_password_api', 16) | b36encode }}"

arvados_cluster_sso_app_secret: "{{ arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_sso_app_secret', 50) | b36encode }}"
arvados_cluster_api_secret_token: "{{ arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_api_secret_token', 50) | b36encode }}"
arvados_cluster_workbench_secret_token: "{{ arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_workbench_secret_token', 50) | b36encode }}"
arvados_cluster_GROUP_blob_signing_key: "{{ arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_blob_signing_key', 50) | b36encode }}"
arvados_cluster_GROUP_blog_signature_ttl_s: 1209600

arvados_cluster_superuser_api_token: "{{  arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_superuser_api_token', 32) | b36encode }}"
arvados_cluster_anonymous_api_token: "{{  arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_anonymous_api_token', 32) | b36encode }}"
arvados_cluster_crunch_dispatcher_api_token: "{{  arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_crunch_dispatcher_api_token', 32) | b36encode }}"
arvados_cluster_GROUP_data_manager_api_token: "{{  arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_data_manager_api_token', 32) | b36encode }}"
arvados_cluster_login_sync_api_token: "{{  arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_login_sync_api_token', 32) | b36encode }}"

arvados_cluster_munge_key_base64: "{{  arvados_cluster_root_key | pbkdf2_hmac('arvados_cluster_munge_key_base64', 1024) | b64encode }}"

arvados_cluster_id: bbpin
arvados_cluster_site_name: "HGI Arvados {{ arvados_cluster_id }}"

arvados_cluster_domain: "hgi.sanger.ac.uk"
arvados_cluster_consul_domain: "node.zeta-hgiarvados-{{ arvados_cluster_id }}.consul"

arvados_cluster_internal_nets:
  - 10.103.0.0/24

arvados_cluster_mercury_shell_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGOhzKGlZVJONd5yYOejP+551myiz2ZiJClMsPZLTiW+pEeSvZZrlbx5qy6fO3cY+AEWOfnl2tTHId+m2wmya5WSqMGFtHfC7Hy7X0iGA2VgfOVfXgDEeYOvlWyjnqKKItT6Uy1tWKrRE7mV50ZPlJISW2Bp32tUk6prchdymRlbSVHzNLV/ieQc4FnQCOu59kC+5oxVpCn8fXJN/r6yHMKPGh14V+mvl4vXQfmgjs0ZL6qz+2EKbPakffcEXqSXp9XKt/DUDpU6YLqOmyctvwXVJGMacRjvcIkiHQG26enmyuOYLpHn0DVGih2JYf4osZr7WvHb78bQv4ptmL3wmx mercury@arvados-shell-{{ arvados_cluster_id }}"

arvados_cluster_git_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbwvszIDZSjS8mHHM97dCXUYL1epVV5FYNGxv57XgqRv2oYa7sFu1fwGkBzwII3GkT8ztaD68LD8xWQXQ+oXOnvda7WW4BBQmSfXuPBUrs0eN8snoFqYNwhoxILhf/8tV8vE2a8Za+wu+Rbx3z+WbbL0IlXZBF8PI2ghYFh7q+pRBRrCg4uCoiP03QPthHdONOUDkMIkj/AM1olOe23FwI5gx2hE1PA1TqFDk+dHhHVPKJxbdZIx6rSmOKRP75RhXpMW+f5N53PgGosUomv+IDAEZ+vnpm01AEj/nkfaapWd24rCXUez31msx3ZN5lhjCkgGIv48pHCRlSCDBjONPr git@{{ arvados_cluster_git_host }}"

arvados_cluster_admin_user_email: "mercury-admin@{{ arvados_cluster_id }}"

arvados_cluster_GROUP_s3_endpoint: "https://{{ s3_credentials['sanger-ceph-mercurykeep']['s3_host'] }}"
arvados_cluster_GROUP_s3_access_key: "{{ s3_credentials['sanger-ceph-mercurykeep']['s3_access_key'] }}"
arvados_cluster_GROUP_s3_secret_key: "{{ s3_credentials['sanger-ceph-mercurykeep']['s3_secret_key'] }}"
arvados_cluster_GROUP_s3_bucket: "arvados-keep-{{ arvados_cluster_id }}"
arvados_cluster_GROUP_s3_replication: 3

arvados_cluster_GROUP_consul_template_host: consul.zeta-hgiarvados-{{ arvados_cluster_id }}.hgi.sanger.ac.uk

# FIXME: Generic stuff below, figure out how to DRY this out

arvados_cluster_sso_user_uuid: "{{ arvados_cluster_id }}-tpzed-mercuryadminsso"

arvados_cluster_shell_server_uuid: "{{ arvados_cluster_id }}-2x53u-shellserver0001"
arvados_cluster_group_name: "arvados-cluster-{{ arvados_cluster_id }}"
arvados_cluster_sso_app_id: arvados-server

arvados_cluster_db_user_sso: arvados_sso
arvados_cluster_db_name_sso: arvados_sso_production

arvados_cluster_db_user_api: arvados
arvados_cluster_db_name_api: arvados_api_production

arvados_cluster_max_body_size_m: 512

# Lists of Arvados server hostvars, names, and hosts (FQDNs)
arvados_cluster_masters: "{{ groups['arvados-masters'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_master_names: "{{ arvados_cluster_masters | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_master_hosts: "{{ arvados_cluster_masters | map(attribute='cloud_resource_fqdn') | list }}"
arvados_cluster_master_private_ips: "{{ arvados_cluster_masters | map(attribute='cloud_resource_private_ip') | list }}"

arvados_cluster_api_dbs: "{{ groups['arvados-api-dbs'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_api_db_names: "{{ arvados_cluster_api_dbs | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_api_db_hosts: "{{ arvados_cluster_api_dbs | map(attribute='cloud_resource_fqdn') | list }}"
arvados_cluster_api_db_private_ips: "{{ arvados_cluster_api_dbs | map(attribute='cloud_resource_private_ip') | list }}"

arvados_cluster_shells: "{{ groups['arvados-shells'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_shell_names: "{{ arvados_cluster_shells | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_shell_hosts: "{{ arvados_cluster_shells | map(attribute='cloud_resource_fqdn') | list }}"

arvados_cluster_keeps: "{{ groups['arvados-keeps'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_keep_names: "{{ arvados_cluster_keeps | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_keep_hosts: "{{ arvados_cluster_keeps | map(attribute='cloud_resource_fqdn_consul') | list }}"

arvados_cluster_keepproxies: "{{ groups['arvados-keepproxies'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_keepproxy_names: "{{ arvados_cluster_keepproxies | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_keepproxy_hosts: "{{ arvados_cluster_keepproxies | map(attribute='cloud_resource_fqdn') | list | map('regex_replace', 'keep', 'keepproxy') | list }}"

arvados_cluster_ssos: "{{ groups['arvados-ssos'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_sso_names: "{{ arvados_cluster_ssos | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_sso_hosts: "{{ arvados_cluster_ssos | map(attribute='cloud_resource_fqdn') | list }}"

arvados_cluster_workbenchs: "{{ groups['arvados-workbenchs'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_workbench_names: "{{ arvados_cluster_workbenchs | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_workbench_hosts: "{{ arvados_cluster_workbenchs | map(attribute='cloud_resource_fqdn') | list }}"

# Public FQDNs of Arvados services
arvados_cluster_sso_host: "arvados-sso-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_api_host: "arvados-api-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_ws_host: "arvados-ws-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_git_host: "arvados-git-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_workbench_host: "arvados-workbench-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_download_host: "arvados-download-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_collections_host: "arvados-collections-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"

arvados_cluster_GROUP_max_compute_nodes: 200

arvados_cluster_GROUP_slurm_control_machine: "arvados-master-{{ arvados_cluster_id }}"

#arvados_cluster_compute_nodes: "{{ groups['arvados-compute-nodes'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
#arvados_cluster_compute_node_names: "{{ arvados_cluster_compute_nodes | map(attribute='cloud_resource_name') | list }}"
#arvados_cluster_compute_node_hosts: "{{ arvados_cluster_compute_nodes | map(attribute='cloud_resource_fqdn') | list }}"

# N.B. the following must match the hostname pattern used in terraform for this cluster
arvados_cluster_GROUP_compute_node_prefix: "arvados-compute-node-{{ arvados_cluster_id }}-"
arvados_cluster_GROUP_compute_node_number_format: "%03d"

arvados_cluster_GROUP_compute_node_pattern: "{{ arvados_cluster_GROUP_compute_node_prefix }}[{{ arvados_cluster_GROUP_compute_node_number_format | format(1) }}-{{ arvados_cluster_GROUP_compute_node_number_format | format(arvados_cluster_GROUP_max_compute_nodes) }}]"
arvados_cluster_GROUP_compute_node_names_lookup_args: "start=1 count={{ arvados_cluster_GROUP_max_compute_nodes }} format={{ arvados_cluster_GROUP_compute_node_prefix }}{{ arvados_cluster_GROUP_compute_node_number_format }}"
arvados_cluster_GROUP_compute_node_names: "{{ lookup('sequence', arvados_cluster_GROUP_compute_node_names_lookup_args, wantlist=True) }}"

arvados_cluster_delegate: "{{ arvados_cluster_shells[0]['inventory_hostname'] }}"

arvados_cluster_exists: "{{ arvados_cluster_shells | length > 0 }}"
