# Copyright (c) 2014, 2015, 2016, 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: site.yml

- import_playbook: hgi-preamble-playbook.yml

# Set up non-host infrastructure
- import_playbook: gitlab-projects.yml

# When image-building, make sure we apply common role even if no other groups apply
- hosts: image-building
  roles:
    - common

# Playbooks that need nonroot host hgi infrastructure
- import_playbook: mesos-masters.yml
- import_playbook: zookeepers.yml
- import_playbook: marathoners.yml
- import_playbook: chronosians.yml
- import_playbook: mesos-slaves.yml
- import_playbook: bamboosians.yml

# We need consul-agents for DNS functionality
# some subsequent roles may not work if they 
# come before (I'm looking at you SLURM)
- import_playbook: consul.yml

# Playbooks that only support root hosts
- import_playbook: arvados.yml
- import_playbook: cookie-jars.yml
- import_playbook: cookie-monsters.yml
- import_playbook: dockerers.yml
- import_playbook: gitlab-runners.yml
- import_playbook: hailers.yml
- import_playbook: openstack-tenant-cleaners.yml
- import_playbook: irobots.yml
#- import_playbook: spark.yml

